version: 2.1

executors:
  default:
    docker:
      - image: cimg/python:3.9

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install System Dependencies
          command: |
            sudo apt update
            sudo apt install -y build-essential
      - run:
          name: Install Python Dependencies
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run Python Script
          command: python file.py

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - branch1
