name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

   - name: Set up Python
     uses: actions/setup-python@v4
     with:
       python-version: 3.10  # Use a valid Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only runs if the 'build' job succeeds

    steps:
    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        # Add deployment commands here
